### ISSUE TITLE
Plugin_config is undocumented

### ISSUE THREAD

**Issue by duffney** [notaryproject/notation-action#48]
I couldn't find any docs on what values are accpeted by the `plugin_config` other than the example that's listed in the readmd. It also wasn't obvious to me how I could use a cert from within my Azure Key Vault instance and not have it locally.

For example:
```yaml
 plugin_config: |-
      name=${{ vars.CERT_NAME }}
      self_signed=false
```

**Comment by FeynmanZhou** [comment]
` plugin_config` means `{key}={value}` pairs that are passed as it is to a plugin, refer plugin's documentation to set appropriate values. This is the same as the flag `plugin_config` in `notation sign`.

See https://notaryproject.dev/docs/user-guides/cli-reference/notation_sign/#options

**Comment by duffney** [comment]
Are there any docs that list out what the `plugin_config` options are? The cli helps says to refer to the plugin docs, but I can't seem to find the docs it referring to.
