### ISSUE TITLE
Request to release Notation GitHub Actions v1.1.0

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/notation-action#61]
We recently upgraded the notation CLI version from v1.1.0 to v1.1.1, added two features #62 and #63 , and upgraded some dependencies.  If we could release a version `v1.1.0` of Notation GHA, it will be convenient for users to use the latest features of Notation in GitHub Actions workflow. Here is the [concreate commit list](https://github.com/notaryproject/notation-action/commits/main/?since=2024-01-31&until=2024-07-10) for the target release v1.1.0.

Repo-level maintainers are suggested voting on this issue:

- [x] @Two-Hearts 
- [x] @duffney

**Comment by Two-Hearts** [comment]
Since there are new features in the main branch, we should do a minor release instead of a patch one. How about `v1.1.0`?
@FeynmanZhou

**Comment by FeynmanZhou** [comment]
@Two-Hearts Agree. I noticed that #62 and #63 are new features that have been merged last week. It's reasonable to cut a minor release instead.

**Comment by FeynmanZhou** [comment]
@duffney @Two-Hearts Now we passed the release vote. We could start the release process soon.

**Comment by duffney** [comment]
My apologies for taking so long to reply. I'll be better about replying in a timely manner.

**Comment by Two-Hearts** [comment]
Completing this issue as v1.1.0 has been released.
