### ISSUE TITLE
Update Notation action to v1.2.0

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/notation-action#76]
These major changes are suggested to be included in notation-action:

- [x] #71 
- [x] OCI v1.1.0 support: `--allow-referrers-api` was deprecated and `--force-referrers-tag` has been introduced to `notation sign`
- [x] Enable users to install Notation v1.2.0 by default

**Comment by Two-Hearts** [comment]
@FeynmanZhou All tasks in this issue have been completed. Since we are going to release Notation CLI v1.3.0 recently, shall we wait for it before releasing notation-action v1.2.0? /cc: @yizha1 @shizhMSFT

**Comment by shizhMSFT** [comment]
I think we can continue to release `v1.2.0`.

**Comment by Two-Hearts** [comment]
Closing as released.
