### ISSUE TITLE
Proposal: Reduce the required number of approvals to `1`

### ISSUE THREAD

**Issue by shizhMSFT** [notaryproject/notation-action#8]
It is currently not reasonable to have 2 approvals for merging a PR where we only have 3 repo-level maintainers and one of them is the PR author.

Therefore, I propose that we should reduce the required number of approvals before merging from `2` to `1` for the `notation-action` repo. Once we have more repo-level maintainers, we can revert the change.

**Comment by yizha1** [comment]
LGTM

**Comment by priteshbandi** [comment]
LGTM

**Comment by duffney** [comment]
LGTM

**Comment by toddysm** [comment]
LGTM. I went ahead and modified the requirement to 1 approval
